project:
  type: website
  output-dir: docs   

website:
  title: "Paul Worlanyo Baka"
  search: true
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Example analysis
        href: example-analysis.qmd
    right:
      - icon: github
        href: https://github.com/pbaka1/biostat777-intro--paul---baka-
      - text: Website
        href: https://pbaka1.github.io/biostat777-intro--paul---baka-/
  page-footer:
    left: "Â© Paul Worlanyo Baka 2025"
    right: |
      <a href="mailto:paulbaka64@gmail.com">Email</a>

format:
  html:
    theme: cosmo
    css: styles.scss      # delete this line if you don't have styles.scss
    toc: true
    toc-depth: 3
    number-sections: false
    smooth-scroll: true
    include-in-header: _icons.html   # remove if you don't want Bootstrap Icons

execute:
  echo: true
  warning: false
  message: false

editor: visual